### ISSUE TITLE
Reset universe when closing Settings

### ISSUE THREAD

**Issue by mamphis** [gandie/PlanetApp#4]
When you changed something in the settings and close the Settings-Page, the universe is been resetted.

**Comment by gandie** [comment]
This is not a bug/issue, it's a feature! ;-)
Did this to ensure settings-changes do not crash the game.
In the future settings should be divided into reset-critical (like starting sunmass, i assume user wants a reset after changing this) and non-critical-in-place-changeable (like planetmass) settings.
Better settings-infrastructure added to TODO-list...
